warehouse_inventory:
  dataset_name: warehouse_inventory

  primary_key: Product ID

  max_missing_percentage: 0.0

  required_columns:
    - Product ID
    - Product Name
    - Category
    - Warehouse
    - Location
    - Quantity
    - Price
    - Status

  optional_columns:
    - Supplier
    - Last Restocked

  expected_data_types:
    Product ID: int64
    Product Name: object
    Category: object
    Warehouse: object
    Location: object
    Quantity: object
    Price: float64
    Supplier: object
    Status: object
    Last Restocked: object


  missing_placeholders:
    - NaN
    - nan
    - NULL
    - null
    - N/A
    - n/a
    - None
    - none

  numeric_columns:
    - Product ID
    - Quantity
    - Price

  date_columns:
    - Last Restocked

  allowed_values:
    Status:
      - In Stock
      - Out of Stock

    Category:
      - ELECTRONICS
      - FURNITURE
      - CLOTHING
      - TOYS

  business_rules:
    quantity_column: Quantity
    quantity_min: 0

    price_column: Price
    price_min: 0

    restocked_date_column: Last Restocked

  compare_columns:
    - Product Name
    - Category
    - Warehouse
    - Location
    - Quantity
    - Price
    - Supplier
    - Status
    - Last Restocked